version: "3"
services:
  frontend:
    image: node:current-alpine
    container_name: node-frontend
    hostname: node-frontend
    working_dir: /home/node/app
    volumes:
      - ./frontend:/home/node/app
    environment:
      NODE_ENV: development
    command: "npm run serve"
    ports:
      - "8080:8080"
    networks:
      - app-network

  backend:
    build: ./dockerize/backend
    image: php-xdebug
    container_name: php-xdebug
    hostname: php-xdebug
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./etc/php/conf:/usr/local/etc/php
      - ./etc/php/logs:/var/log/php
      - ./backend:/var/www/html
    networks:
      - app-network

  http:
    image: nginx:alpine
    container_name: nginx-app
    hostname: nginx
    volumes:
      - ./etc/nginx/conf.d/nginx.conf:/etc/nginx/nginx.conf
      - ./etc/nginx/logs:/var/log/nginx
      - ./backend:/usr/share/nginx/html
    ports:
      - "80:80"
    networks:
      - app-network

  database:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - app-network

volumes:
  dbdata:
    driver: local

networks:
  app-network:
    driver: bridge
